---
- name: real_world_condition_example
  hosts: web
  become: yes
  tasks:
    - name: install_nginx
      yum:
        name: nginx
        state: latest
      notify: nginx_installed
  handlers: 
    - name: nginx_installed
      service:
        name: nginx
        state: started
