---
- name: install nginx ( play name )
  hosts: 
   - web
   - web1
  become: yes
  tasks:
   - name: install nginx ( task name )
     yum:
       name: nginx
       state: latest
   - name: install node ( task name )
     yum:
       name: nodejs
       state: latest
   - name: starting nginx (task name)
     service:
       name: nginx
       state: started 
